name: Copilot Setup (Pre-Firewall)
steps:
  - name: Setup Node
    uses: actions/setup-node@v4
    with:
      node-version: 20
      cache: npm
  - name: Install deps
    run: npm ci
  - name: Install Playwright (Chromium only)
    run: npx playwright install chromium
