# This file runs BEFORE the agent firewall in its ephemeral environment.
# Keep it minimal—no external apt, no dev servers—just installs Node deps.

steps:
  - run: node -v && npm -v
  - run: npm ci
  - run: npm run typecheck || true
  - run: npm run lint || true
  # Do not run vite/playwright here in agent sandbox.
