# Pre-install steps for Copilot agent before firewall comes up
# Works across all Spark repos (council, chess, rap game)

setup:
  steps:
    # 1. Ensure correct Node version
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    # 2. Install all dependencies with lockfile
    - name: Install dependencies
      run: npm ci

    # 3. Build before tests (avoids vite runtime calls under firewall)
    - name: Build app
      run: npm run build

    # 4. Run lint & type check (gives Copilot a clean slate)
    - name: Validate project
      run: |
        npm run lint || echo "Lint errors (non-blocking)"
        npm run typecheck || echo "Type errors (non-blocking)"

    # 6. Install Playwright deps if E2E is present
    - name: Install Playwright browsers
      run: npx playwright install --with-deps

    # 7. Confirm all scripts are available
    - name: List available scripts
      run: |
        echo "=== Available Scripts ==="
        jq '.scripts' package.json
