name: CI (Offline E2E)

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - run: npx playwright install --with-deps chromium
      - run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: app-dist
          path: dist
      - uses: actions/upload-artifact@v4
        with:
          name: pw-browsers
          path: ~/.cache/ms-playwright
        if: ${{ !env.PLAYWRIGHT_BROWSERS_PATH }}
      - uses: actions/upload-artifact@v4
        with:
          name: node-modules
          path: node_modules
        if-no-files-found: ignore

  test-offline:
    runs-on: ubuntu-latest
    needs: build
    env:
      PLAYWRIGHT_BROWSERS_PATH: ${{ github.workspace }}/.playwright-browsers
      PLAYWRIGHT_SKIP_VALIDATE_HOST_REQUIREMENTS: '1'
      CI: 'true'
    steps:
      - uses: actions/checkout@v4

      - name: Download dist
        uses: actions/download-artifact@v4
        with:
          name: app-dist
          path: dist

      - name: Download browsers
        uses: actions/download-artifact@v4
        with:
          name: pw-browsers
          path: .playwright-browsers

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Restore node_modules (optional)
        uses: actions/download-artifact@v4
        with:
          name: node-modules
          path: node_modules
        continue-on-error: true

      - name: Install minimal test deps if needed
        run: |
          npm pkg get devDependencies['serve-handler'] | grep -vq null || npm i -D serve-handler
          npm pkg get devDependencies['@playwright/test'] | grep -vq null || npm i -D @playwright/test

      - name: Run E2E (no external network)
        run: npx playwright test --reporter=line
