name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    env:
      # Disable Ubuntu Pro / ESM repository access
      DEBIAN_FRONTEND: noninteractive
      # Mock GitHub API responses locally
      GITHUB_API_MOCK: "true"
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Configure apt to skip esm.ubuntu.com
      run: |
        # Disable Ubuntu Pro / ESM repositories to avoid firewall blocks
        sudo rm -f /etc/apt/sources.list.d/ubuntu-esm-*.list 2>/dev/null || true
        sudo sed -i '/esm\.ubuntu\.com/d' /etc/apt/sources.list 2>/dev/null || true
        echo "✅ ESM repositories disabled"
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linter
      run: npm run lint
      continue-on-error: true
    
    - name: Run build
      run: npm run build
    
    - name: Install Playwright browsers
      run: npx playwright install chromium --with-deps
    
    - name: Run E2E tests
      run: npm run test:e2e
      env:
        # Ensure tests only hit localhost
        CI: true
    
    - name: Run pre-publish checks
      run: ./scripts/pre-publish-check.sh
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test-results/
        retention-days: 7
